[package]
name = "mp-hashers"
version.workspace = true
edition.workspace = true
license = "MIT"
description = "Starknet hashers"
authors = { workspace = true }
repository = { workspace = true }

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]

[dependencies]
mp-felt = { workspace = true }
serde = { workspace = true }
starknet-core = { workspace = true }
starknet-crypto = { workspace = true }
