[package]
authors.workspace = true
edition.workspace = true
name = "dp-convert"
repository.workspace = true
version.workspace = true

[dependencies]
starknet-core = { workspace = true }
starknet-ff = { workspace = true }
starknet-providers = { workspace = true }
starknet-types-core = { workspace = true }
starknet_api = { workspace = true }
