[package]
authors.workspace = true
edition.workspace = true
name = "mp-convert"
repository.workspace = true
version.workspace = true

[dependencies]
anyhow = { workspace = true }
blockifier = { workspace = true }
cairo-lang-starknet-classes = { workspace = true }
cairo-lang-utils = { workspace = true }
cairo-vm = { workspace = true }
flate2 = { workspace = true }
indexmap = { workspace = true }
mp-felt = { workspace = true }
mp-transactions = { workspace = true }
num-bigint = { workspace = true }
scale-info = { workspace = true, features = ["derive"] }
serde_json = { workspace = true }
starknet-core = { workspace = true }
starknet-providers = { workspace = true }
starknet_api = { workspace = true }

[features]
default = ["std"]
std = ["anyhow/std", "num-bigint/std"]
