[package]
description = "Deoxys primitive for type conversion"
name = "dp-convert"
authors.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
version.workspace = true
homepage.workspace = true

[dependencies]
starknet-core = { workspace = true }
starknet-ff = { workspace = true }
starknet-providers = { workspace = true }
starknet-types-core = { workspace = true }
starknet_api = { workspace = true }
