[workspace]
members = [
  "crates/client/db",
  "crates/client/sync",
  "crates/client/rpc",
  "crates/client/telemetry",
  "crates/node",
  "crates/primitives/block",
  "crates/primitives/convert",
  "crates/primitives/felt",
  "crates/primitives/hashers",
  "crates/primitives/program-hash",
  "crates/primitives/transactions",
  "crates/primitives/types",
]
resolver = "2"
# All previous except for `starknet-rpc-test` and `starknet-e2e-test`
# We don't want `cargo test` to trigger its tests
default-members = [
  "crates/client/db",
  "crates/client/sync",
  "crates/client/rpc",
  "crates/client/telemetry",
  "crates/node",
  "crates/primitives/block",
  "crates/primitives/felt",
  "crates/primitives/hashers",
  "crates/primitives/program-hash",
  "crates/primitives/transactions",
  "crates/primitives/types",
]

[profile.dev]
incremental = true
panic = "abort"

[profile.release]
panic = "unwind"

[profile.production]
codegen-units = 1    # Setting this to 1 allows for more optimizations at the cost of slower compile time
inherits = "release"
lto = "fat"          # Enables Link Time Optimization, enabling more aggressive optimizations across the entire codebase
opt-level = 3        # Optimize for speed regardless of binary size or compile time
rpath = false        # Disables adding rpath to the binary
strip = "symbols"    # Removes debug info and symbold from final binary

[workspace.package]
authors = ["Antiyro <@antiyro>"]
edition = "2021"
repository = "https://github.com/kasarlabs/deoxys/"
version = "0.1.0"

[workspace.dependencies]
rocksdb = { version = "0.21", features = [
  # "multi-threaded-cf",
] }

# Substrate build & tools dependencies
prometheus-endpoint = { package = "substrate-prometheus-endpoint", version = "0.10.0-dev", git = "https://github.com/kasarlabs/polkadot-sdk", branch = "release-polkadot-v1.3.0-std" }
parity-scale-codec = { version = "3.2", default-features = false, features = [
  "std",
] }

# Bonsai trie dependencies
bonsai-trie = { default-features = false, git = "https://github.com/keep-starknet-strange/bonsai-trie.git", branch = "oss", features = [
  "std",
] }

# Deoxys primtitives
mp-block = { path = "crates/primitives/block", default-features = false }
mp-convert = { path = "crates/primitives/convert", default-features = false }
mp-felt = { path = "crates/primitives/felt", default-features = false }
mp-hashers = { path = "crates/primitives/hashers", default-features = false }
mp-program-hash = { path = "crates/primitives/program-hash", default-features = false }
mp-sequencer-address = { path = "crates/primitives/sequencer-address", default-features = false }
mp-simulations = { path = "crates/primitives/simulations", default-features = false }
mp-transactions = { path = "crates/primitives/transactions", default-features = false }
mp-types = { path = "crates/primitives/types", default-features = false }

# Deoxys client
mc-telemetry = { path = "crates/client/telemetry" }
mc-db = { path = "crates/client/db" }
mc-rpc = { path = "crates/client/rpc" }
mc-sync = { path = "crates/client/sync", default-features = false }

# Starknet dependencies
# Cairo Virtual Machine
cairo-vm = { git = "https://github.com/kasarlabs/cairo-vm", branch = "feature/scale-codec", default-features = false, features = [
  "cairo-1-hints",
  "parity-scale-codec",
  "std",
] }
starknet-core = { git = "https://github.com/kasarlabs/starknet-rs.git", branch = "fork", default-features = false }
starknet-crypto = { git = "https://github.com/kasarlabs/starknet-rs.git", branch = "fork", default-features = false }
starknet-ff = { git = "https://github.com/kasarlabs/starknet-rs.git", branch = "fork", default-features = false }
starknet-providers = { git = "https://github.com/kasarlabs/starknet-rs.git", branch = "fork", default-features = false }

starknet-types-core = { version = "0.1", default-features = false, features = [
  "hash",
  "parity-scale-codec",
] }

blockifier = { git = "https://github.com/kasarlabs/blockifier", branch = "feature/scale-codec-v6" }
starknet_api = { git = "https://github.com/kasarlabs/starknet-api", branch = "feature/scale-codec", features = [
  "testing",
  "parity-scale-codec",
] }
cairo-lang-starknet-classes = { git = "https://github.com/kasarlabs/cairo.git", branch = "feature/scale-codec" }
cairo-lang-utils = { git = "https://github.com/kasarlabs/cairo.git", branch = "feature/scale-codec" }

# Ethers: using the same versions as in Anvil
ethers = { git = "https://github.com/gakonst/ethers-rs" }

# Other third party dependencies
anyhow = "1.0"
assert_matches = "1.5"
async-trait = "0.1"
bitvec = { version = "1.0", default-features = false, features = ["std"] }
base64 = "0.13"
clap = { version = "4.4", default-features = false, features = ["std"] }
derive_more = { version = "0.99", default-features = false }
flate2 = "1.0"
futures = { version = "0.3", default-features = false, features = ["std"] }
hex = { version = "0.4", default-features = false, features = ["std"] }
indexmap = "2.2"
itertools = "0.12"
jsonrpsee = { version = "0.22", default-features = false, features = [
  "server",
] }
tower = { version = "0.4", features = ["util"] }
tower-http = { version = "0.4", features = ["cors"] }
governor = "0.6"
hyper = { version = "0.14", features = ["server"] }
ip_network = "0.4"
lazy_static = { version = "1.4", default-features = false }
once_cell = "1.19"
log = { version = "0.4", default-features = false, features = ["std"] }
num-traits = "0.2"
num-bigint = "0.4"
primitive-types = "0.12"
rand = "0.8"
reqwest = { version = "0.12", features = ["json"] }
rstest = "0.18"
scale-info = { version = "2.10", default-features = false, features = ["std"] }
serde = { version = "1.0", default-features = false, features = ["std"] }
serde_json = { version = "1.0", default-features = false, features = ["std"] }
serde_with = { version = "2.3", default-features = false }
thiserror = "1.0"
thiserror-no-std = "2.0"
tokio = "1.34"
url = "2.4"
rayon = "1.10"
crossbeam-skiplist = "0.1"
bincode = "1.3"
