version: '3.8'

services:
  deoxys:
    build:
      context: ./deoxys/
      dockerfile: Dockerfile
    container_name: deoxys
    restart: unless-stopped
    ports:
      - "9944:9944"
    volumes:
      - /var/lib/deoxys:/var/lib/deoxys
    command: ["--deoxys", "--rpc-port", "9944", "--network", "main", "--rpc-external", "--rpc-cors", "*", "--l1-endpoint", "${ETHEREUM_API_URL}", "--base-path", "/var/lib/deoxys"]
