[package]
authors = [
  "Kasar <https://github.com/kasarlabs>",
  "Keep Starknet Strange <https://github.com/keep-starknet-strange>",
  "Substrate DevHub <https://github.com/substrate-developer-hub>",
]
description = "FRAME pallet to execute Starknet contracts."
edition.workspace = true
homepage = "https://github.com/kasarlabs/deoxys"
license = "MIT"
name = "pallet-starknet"
publish = false
repository = "https://github.com/kasarlabs/deoxys"
version.workspace = true

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]

[dependencies]
# Deoxys primitives
mc-db = { workspace = true }
mp-block = { workspace = true }
mp-contract = { workspace = true }
mp-digest-log = { workspace = true }
mp-felt = { workspace = true, features = ["parity-scale-codec", "serde"] }
mp-genesis-config = { workspace = true, default-features = false }
mp-hashers = { workspace = true }
mp-sequencer-address = { workspace = true, features = ["parity-scale-codec"] }
mp-simulations = { workspace = true, features = [
  "parity-scale-codec",
  "scale-info",
] }
mp-storage = { workspace = true, features = ["parity-scale-codec"] }
mp-transactions = { workspace = true, features = ["scale-info"] }

blockifier = { workspace = true, features = ["testing"] }

starknet-core = { workspace = true }
starknet-crypto = { workspace = true, features = ["alloc"] }
starknet_api = { workspace = true }

# Substrate frame
frame-benchmarking = { workspace = true, optional = true }
frame-support = { workspace = true }
frame-system = { workspace = true }
# Substrate primitives
cairo-vm = { workspace = true }
sp-api = { workspace = true }
sp-arithmetic = { workspace = true }
sp-core = { workspace = true }
sp-inherents = { workspace = true }
sp-io = { workspace = true }
sp-runtime = { workspace = true }
sp-std = { workspace = true }
# Frame pallets

# Other third party dependencies
cairo-lang-starknet-classes = { workspace = true, optional = true }
derive_more = { workspace = true }
hex = { workspace = true }
indexmap = { workspace = true }
itertools = { workspace = true }
log = { workspace = true }
parity-scale-codec = { workspace = true, features = ["derive"] }
reqwest = { workspace = true, optional = true, features = [
  "blocking",
  "rustls-tls",
] }
scale-info = { workspace = true, features = ["derive"] }
serde = { workspace = true, features = ["derive"] }
serde_json = { workspace = true }
serde_with = { workspace = true }

[dev-dependencies]
assert_matches = { workspace = true }
lazy_static = { workspace = true }
starknet-ff = { workspace = true }

[features]
default = ["std"]
runtime-benchmarks = ["frame-benchmarking/runtime-benchmarks"]
std = [
  # Substrate
  "frame-benchmarking?/std",
  "frame-support/std",
  "frame-system/std",
  "scale-info/std",
  "sp-inherents/std",
  "sp-io/std",
  "sp-runtime/std",
  # Starknet
  "mp-felt/std",
  "mp-genesis-config/std",
  "mp-sequencer-address/std",
  "starknet-crypto/std",
  # Other third party dependencies
  "dep:reqwest",
  "mp-block/std",
  "mp-contract/std",
  "mp-simulations/std",
  "parity-scale-codec/std",
  "starknet-core/std",
  "cairo-lang-starknet-classes",
]
try-runtime = ["frame-support/try-runtime"]
