[package]
description = "Deoxys utilities"
name = "dp-utils"
authors.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
version.workspace = true
homepage.workspace = true

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]

[dependencies]

# Orher
futures.workspace = true
rayon.workspace = true
tokio.workspace = true
