[package]
description = "This crate is responsible to handle l1 communication"
name = "mc-settlement-client"
authors.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
version.workspace = true
homepage.workspace = true

[lints.clippy]
# We cannot inherit the lints because the sol! macro for solidy ABI generates unsafe blocks.
print_stdout = "warn"
print_stderr = "warn"

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]

[dependencies]

# Madara
mc-analytics.workspace = true
mc-db.workspace = true
mc-mempool.workspace = true
mp-chain-config.workspace = true
mp-convert.workspace = true
mp-transactions.workspace = true
mp-utils.workspace = true

# Starknet
starknet-types-core.workspace = true
starknet_api.workspace = true


# Other
alloy.workspace = true
anyhow.workspace = true
assert_matches = "1.5.0"
bigdecimal.workspace = true
bitvec.workspace = true
futures = { workspace = true, default-features = true }
mockall.workspace = true
regex = "1.10.5"
serde = { workspace = true, default-features = true }
serde_json = "1"
starknet-accounts = "0.11.0"
starknet-contract = "0.11.0"
starknet-core = { workspace = true }
starknet-crypto = { workspace = true }
starknet-providers = { workspace = true }
starknet-signers = { workspace = true }
thiserror.workspace = true
time = "0.3.36"
tokio = { workspace = true, features = [
  "macros",
  "parking_lot",
  "test-util",
  "signal",
] }
url.workspace = true


#Instrumentation
async-trait = { workspace = true }
hex = "0.4.3"
log = "0.4.22"
matchers = "0.1.0"
opentelemetry = { workspace = true, features = ["metrics", "logs"] }
opentelemetry-appender-tracing = { workspace = true, default-features = false }
opentelemetry-otlp = { workspace = true, features = [
  "tonic",
  "metrics",
  "logs",
] }
opentelemetry-semantic-conventions = { workspace = true }
opentelemetry-stdout = { workspace = true }
opentelemetry_sdk = { workspace = true, features = ["rt-tokio", "logs"] }
reqwest = "0.11.27"
tracing = { workspace = true }
tracing-core = { workspace = true, default-features = false }
tracing-opentelemetry = { workspace = true }
tracing-subscriber = { workspace = true, features = ["env-filter"] }


[features]
default = []

[dev-dependencies]
rstest.workspace = true
once_cell.workspace = true
tempfile.workspace = true
dotenv.workspace = true
httpmock.workspace = true
serial_test.workspace = true
tracing-test = "0.2.5"
lazy_static.workspace = true
mp-utils = { workspace = true, features = ["testing"] }
mc-mempool = { workspace = true, features = ["testing"] }
# Compile the test contracts in test cfg.
m-cairo-test-contracts.workspace = true
