[package]
name = "dc-db"
version.workspace = true
edition.workspace = true
description = "Starknet database backend"
authors = ["Kasar <https://github.com/kasarlabs>"]
homepage = "https://github.com/kasarlabs/deoxys"
license = "MIT"
publish = false
repository = "https://github.com/kasarlabs/deoxys"

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]

[dependencies]
cairo-vm = { workspace = true }
flate2 = { workspace = true }

# Deoxys crates
dp-block = { workspace = true }
dp-convert = { workspace = true }
dp-transactions = { workspace = true }
dp-utils = { workspace = true }

# Starknet crates
blockifier = { workspace = true }
bonsai-trie = { workspace = true }
starknet-core = { workspace = true }
starknet-ff = { workspace = true }
starknet-types-core = { workspace = true }
starknet_api = { workspace = true }

# Other crates
anyhow.workspace = true
async-trait = { workspace = true }
base64 = { workspace = true }
bincode = { workspace = true }
bitvec = { workspace = true }
crossbeam-skiplist = { workspace = true }
indexmap = { workspace = true }
log = { workspace = true, default-features = true }
parity-scale-codec = { version = "3.6.5", features = ["derive"] }
rayon = { workspace = true }
rocksdb.workspace = true
thiserror = { workspace = true }
tokio = { workspace = true }
