[package]
name = "mc-db"
version.workspace = true
edition.workspace = true
description = "Starknet database backend"
authors = [
  "Kasar <https://github.com/kasarlabs>",
  "Keep Starknet Strange <https://github.com/keep-starknet-strange>",
  "Substrate DevHub <https://github.com/substrate-developer-hub>",
]
homepage = "https://github.com/kasarlabs/deoxys"
license = "MIT"
publish = false
repository = "https://github.com/kasarlabs/deoxys"

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]

[dependencies]
# Substrate crates
parity-scale-codec = { workspace = true, default-features = true, features = [
  "derive",
] }
sc-client-db = { workspace = true, default-features = true }
sp-core = { workspace = true }
sp-database = { workspace = true, default-features = true }
sp-runtime = { workspace = true, default-features = true }

# Deoxys crates
mp-block = { workspace = true }
mp-contract = { workspace = true }
mp-felt = { workspace = true }
mp-hashers = { workspace = true }
mp-types = { workspace = true }

# Starknet crates
blockifier = { workspace = true, features = ["testing"] }
bonsai-trie = { workspace = true }
starknet-core = { workspace = true }
starknet-ff = { workspace = true, default-features = false, features = [
  "alloc",
  "serde",
] }
starknet-types-core = { workspace = true, default-features = false, features = [
  "hash",
  "parity-scale-codec",
] }
starknet_api = { workspace = true, default-features = true }

# Other crates
anyhow.workspace = true
arc-swap = { workspace = true }
async-trait = { workspace = true }
bitvec = { workspace = true }
crossbeam-skiplist = { workspace = true }
ethers = { workspace = true }
log = { workspace = true, default-features = true }
rayon = { workspace = true }
rocksdb = { version = "0.21", features = [
  # "multi-threaded-cf",
] }
serde_json = { workspace = true }
thiserror = { workspace = true }
tokio = { workspace = true }
uuid = "1.4.1"
