[package]
name = "dc-db"
description = "Deoxys client database service"
authors.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
version.workspace = true
homepage.workspace = true

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]

[dependencies]

# Deoxys
dp-block = { workspace = true }
dp-class = { workspace = true }
dp-convert = { workspace = true }
dp-transactions = { workspace = true }

# Starknet
blockifier = { workspace = true }
bonsai-trie = { workspace = true }
cairo-vm = { workspace = true }
starknet-core = { workspace = true }
starknet-providers = { workspace = true }
starknet-types-core = { workspace = true }
starknet_api = { workspace = true }

# Other
anyhow.workspace = true
async-trait = { workspace = true }
base64 = { workspace = true }
bincode = { workspace = true }
bitvec = { workspace = true }
crossbeam-skiplist = { workspace = true }
flate2 = { workspace = true }
indexmap = { workspace = true }
log = { workspace = true, default-features = true }
parity-scale-codec = { version = "3.6.5", features = ["derive"] }
rayon = { workspace = true }
rocksdb.workspace = true
serde = { workspace = true }
serde_json = { workspace = true }
thiserror = { workspace = true }
tokio = { workspace = true }
