[package]
name = "mc-db"
version.workspace = true
edition.workspace = true
description = "Starknet database backend"
authors = [
  "Kasar <https://github.com/kasarlabs>",
  "KSS <https://github.com/keep-starknet-strange>",
  "Substrate DevHub <https://github.com/substrate-developer-hub>",
]
homepage = "https://github.com/kasarlabs/deoxys"
license = "MIT"
publish = false
repository = "https://github.com/kasarlabs/deoxys"

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]

[dependencies]
cairo-lang-starknet-classes = { workspace = true }
cairo-vm = { workspace = true }
flate2 = { workspace = true }
indexmap = { workspace = true }
parity-scale-codec = { workspace = true, default-features = true, features = [
  "derive",
] }

# Deoxys crates
mp-block = { workspace = true }
mp-convert = { workspace = true }
mp-felt = { workspace = true }
mp-transactions = { workspace = true }

# Starknet crates
blockifier = { workspace = true }
bonsai-trie = { workspace = true }
starknet-core = { workspace = true }
starknet-ff = { workspace = true }
starknet-types-core = { workspace = true }
starknet_api = { workspace = true }

# Other crates
anyhow.workspace = true
async-trait = { workspace = true }
base64 = { workspace = true }
bincode = { workspace = true }
bitvec = { workspace = true }
crossbeam-skiplist = { workspace = true }
itertools = { workspace = true }
log = { workspace = true, default-features = true }
rayon = { workspace = true }
rocksdb.workspace = true
serde = { workspace = true }
serde_json = { workspace = true }
thiserror = { workspace = true }
tokio = { workspace = true }
