[package]
name = "dc-db"
description = "Deoxys client database service"
authors.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
version.workspace = true
homepage.workspace = true

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]

[dependencies]

# Deoxys
dc-metrics = { workspace = true }
dp-block = { workspace = true }
dp-class = { workspace = true }
dp-state-update = { workspace = true }
dp-transactions = { workspace = true }
dp-utils = { workspace = true }

# Starknet
bonsai-trie = { workspace = true }
starknet-core = { workspace = true }
starknet-types-core = { workspace = true }
starknet_api = { workspace = true }

# Other
anyhow.workspace = true
bincode = { workspace = true }
log = { workspace = true, default-features = true }
rayon = { workspace = true }
rocksdb.workspace = true
serde = { workspace = true }
thiserror = { workspace = true }
tokio = { workspace = true, features = [
  "macros",
  "parking_lot",
  "test-util",
  "signal",
] }

[dev-dependencies]
tempfile = "3.10"
lazy_static = { workspace = true }
dp-transactions = { workspace = true }
dp-receipt = { workspace = true }
