[package]
name = "dp-transactions"
version.workspace = true
edition.workspace = true
license = "MIT"
description = "Starknet primitives for Substrate."
authors = { workspace = true }
repository = { workspace = true }

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]

[dependencies]
blockifier = { workspace = true }
cairo-lang-starknet-classes = { workspace = true }
cairo-lang-utils = { workspace = true }
cairo-vm = { workspace = true }
dp-felt = { workspace = true }
flate2 = { workspace = true }
indexmap = { workspace = true }
num-bigint = { workspace = true }
serde = { workspace = true, features = ["derive"] }
serde_json = { workspace = true }
starknet-core = { workspace = true }
starknet-crypto = { workspace = true }
starknet-types-core = { workspace = true }
starknet_api = { workspace = true }
thiserror = { workspace = true }

dp-convert = { workspace = true }

[dev-dependencies]
assert_matches = { workspace = true }
