---
blank_issues_enabled: true

contact_links:
  - name: Support & Troubleshooting with Madara Community
    url: https://t.me/madara
    about: >-
      For general problems with Madara or related technologies, please ask
      questions in our community! We highly encourage everyone to also share
      their understanding by answering questions for others.
