[package]
authors = { workspace = true }
description = "The starknet block"
edition.workspace = true
license = "MIT"
name = "mp-block"
repository = { workspace = true }
version.workspace = true

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]

[dependencies]
blockifier = { workspace = true }
lazy_static = { workspace = true }
mp-felt = { workspace = true }
serde = { workspace = true, features = ["derive"] }
serde_json = { workspace = true }
starknet-core = { workspace = true }
starknet-types-core = { workspace = true }
starknet_api = { workspace = true }

# Optionals
mp-convert = { workspace = true }
primitive-types.workspace = true

[dev-dependencies]
mp-felt = { workspace = true }
