[package]
authors = { workspace = true }
description = "The starknet block"
edition.workspace = true
license = "MIT"
name = "dp-block"
repository = { workspace = true }
version.workspace = true

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]

[dependencies]
blockifier = { workspace = true }
dp-felt = { workspace = true }
lazy_static = { workspace = true }
serde = { workspace = true, features = ["derive"] }
serde_json = { workspace = true }
starknet-core = { workspace = true }
starknet-types-core = { workspace = true }
starknet_api = { workspace = true }

# Optionals
dp-convert = { workspace = true }
primitive-types.workspace = true

[dev-dependencies]
dp-felt = { workspace = true }
