[package]
authors = { workspace = true }
description = "The starknet block"
edition.workspace = true
license = "MIT"
name = "mp-block"
repository = { workspace = true }
version.workspace = true

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]

[dependencies]
blockifier = { workspace = true }
lazy_static = { workspace = true }
mp-felt = { workspace = true }
serde = { workspace = true, features = ["derive"], optional = true }
serde_json = { workspace = true }
starknet-core = { workspace = true }
starknet-types-core = { workspace = true }
starknet_api = { workspace = true }
log = { workspace = true }

# Optionals
anyhow = { workspace = true, optional = true }
parity-scale-codec = { workspace = true, features = [
  "derive",
], optional = true }
primitive-types.workspace = true
scale-info = { workspace = true, features = ["derive"], optional = true }

[dev-dependencies]
mp-felt = { workspace = true }

[features]
default = ["std"]
parity-scale-codec = ["dep:parity-scale-codec", "mp-felt/parity-scale-codec"]
scale-info = ["dep:scale-info"]
std = [
  "mp-felt/std",
  "serde/std",
  # Optionals
  "anyhow",
  "parity-scale-codec?/std",
  "scale-info?/std",
]
