[package]
description = "Madara primitives for starknet blocks"
name = "mp-block"
authors.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
version.workspace = true
homepage.workspace = true

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]

[dependencies]

# Madara
mp-chain-config = { workspace = true }
mp-convert = { workspace = true }
mp-receipt = { workspace = true }
mp-transactions = { workspace = true }

# Starknet
blockifier = { workspace = true }
starknet-core = { workspace = true }
starknet-types-core = { workspace = true }
starknet_api = { workspace = true }

# Other
lazy_static = { workspace = true }
primitive-types.workspace = true
serde = { workspace = true, features = ["derive"] }
serde_json = { workspace = true }
thiserror = { workspace = true }
