[package]
name = "deoxys"
description = "Deoxys node"
authors.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
version.workspace = true
homepage.workspace = true
build = "build.rs"

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]

[[bin]]
name = "deoxys"

[dependencies]
clap = { workspace = true, features = ["derive"] }
dc-telemetry = { workspace = true }
futures = { workspace = true, features = ["thread-pool"] }
log = { workspace = true }
tokio = { workspace = true }

# Starknet
dc-db = { workspace = true }
dc-metrics = { workspace = true }
dc-rpc = { workspace = true }
starknet-core = { workspace = true }
starknet-providers = { workspace = true }
starknet-types-core = { workspace = true }

# Primitives
dp-utils = { workspace = true }
primitive-types = { workspace = true }

#Deoxys
dc-sync = { workspace = true }
reqwest = { workspace = true }
url = { workspace = true }

anyhow.workspace = true
chrono = "0.4.38"
env_logger = "0.11.3"
forwarded-header-value = "0.1.1"
governor.workspace = true
hyper.workspace = true
ip_network.workspace = true
jsonrpsee.workspace = true
rayon.workspace = true
serde_json.workspace = true
thiserror.workspace = true
tower-http.workspace = true
tower.workspace = true

[features]
default = []
sound = ["dc-sync/m"]
