[package]
name = "dc-rpc"
description = "Deoxys client rpc service"
authors.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
version.workspace = true
homepage.workspace = true

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]

[dependencies]

# Deoxys
dc-db = { workspace = true }
dc-exec = { workspace = true }
dp-block = { workspace = true, default-features = true }
dp-class = { workspace = true }
dp-convert = { workspace = true, default-features = true }
dp-receipt = { workspace = true }
dp-transactions = { workspace = true }

# Starknet
blockifier = { workspace = true, default-features = true }
starknet-core = { workspace = true }
starknet-providers = { workspace = true }
starknet-types-core = { workspace = true }
starknet_api = { workspace = true, default-features = true }

# Others
anyhow = { workspace = true }
jsonrpsee = { workspace = true, default-features = true, features = [
  "macros",
  "server",
] }
log = { workspace = true, default-features = true }
thiserror = { workspace = true }

[dev-dependencies]
rstest = { workspace = true }
