[package]
authors = [
  "Kasar <https://github.com/kasarlabs>",
  "KSS <https://github.com/keep-starknet-strange>",
  "Substrate DevHub <https://github.com/substrate-developer-hub>",
]
description = "Starknet RPC compatibility layer for Substrate"
edition.workspace = true
homepage = "https://github.com/kasarlabs/deoxys"
license = "MIT"
name = "mc-rpc"
publish = false
repository = "https://github.com/kasarlabs/deoxys"
version.workspace = true

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]

[dependencies]
# Deoxys client
mc-db = { workspace = true }
mc-sync = { workspace = true }

# Starknet
blockifier = { workspace = true, default-features = true }
starknet-core = { workspace = true }
starknet-ff = { workspace = true }
starknet-providers = { workspace = true }
starknet_api = { workspace = true, default-features = true }

# Others
anyhow = { workspace = true }
cairo-vm = { workspace = true }
indexmap = { workspace = true }
itertools = { workspace = true }
jsonrpsee = { workspace = true, default-features = true, features = [
  "macros",
  "server",
] }
log = { workspace = true, default-features = true }
mp-block = { workspace = true, default-features = true }
mp-convert = { workspace = true, default-features = true }
mp-felt = { workspace = true, default-features = true }
mp-hashers = { workspace = true, default-features = true }
mp-simulations = { workspace = true }
mp-transactions = { workspace = true, features = ["client"] }
mp-types = { workspace = true }
serde = { workspace = true, default-features = true }
serde_with = { workspace = true }
thiserror = { workspace = true }

[dev-dependencies]
rstest = { workspace = true }
