[package]
authors = ["Kasar <https://github.com/kasarlabs>"]
description = "Starknet RPC compatibility layer for Substrate"
edition.workspace = true
homepage = "https://github.com/kasarlabs/deoxys"
license = "MIT"
name = "dc-rpc"
publish = false
repository = "https://github.com/kasarlabs/deoxys"
version.workspace = true

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]

[dependencies]
# Deoxys client
dc-db = { workspace = true }

# Starknet
blockifier = { workspace = true, default-features = true }
starknet-core = { workspace = true }
starknet-ff = { workspace = true }
starknet-providers = { workspace = true }
starknet_api = { workspace = true, default-features = true }

# Others
anyhow = { workspace = true }
cairo-vm = { workspace = true }
dp-block = { workspace = true, default-features = true }
dp-convert = { workspace = true, default-features = true }
dp-felt = { workspace = true, default-features = true }
dp-simulations = { workspace = true }
dp-transactions = { workspace = true }
indexmap = { workspace = true }
itertools = { workspace = true }
jsonrpsee = { workspace = true, default-features = true, features = [
  "macros",
  "server",
] }
log = { workspace = true, default-features = true }
serde = { workspace = true, default-features = true }
serde_with = { workspace = true }
thiserror = { workspace = true }

[dev-dependencies]
rstest = { workspace = true }
