[package]
name = "mp-simulations"
version.workspace = true
edition.workspace = true
license = "MIT"
description = "Starknet chain ids"
authors = { workspace = true }
repository = { workspace = true }

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]

[dependencies]
starknet-core = { workspace = true }
