[package]
description = "Deoxys primitive for transaction simulation"
name = "dp-simulations"
authors.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
version.workspace = true
homepage.workspace = true

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]

[dependencies]

# Starknet
starknet-core = { workspace = true }
