[package]
name = "mc-deoxys"
version = "0.1.0"
description = "Deoxys crate for Madara"
authors = [
    "Antiyro <https://github.com/antiyro>",
]
homepage = "https://github.com/KasarLabs/deoxys"
edition = "2021"
license = "MIT"
publish = false
repository = "https://github.com/KasarLabs/deoxys"

[features]
default = ["m"]
m = ["dep:rodio"]

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]

[dependencies]
starknet-gateway = "0.6"
reqwest = "0.11"
serde_json = "1"
anyhow = "1.0.75"
web3 = "0.19.0"
tokio-tungstenite = "0.20.1"
lazy_static = "1.4.0"

url = { workspace = true }
serde = { workspace = true, default-features = true }
rodio = { version = "0.17", optional = true }
rand = { version = "0.8.5" }
indexmap = { workspace = true }
blockifier = { workspace = true, default-features = false, features = [
    "testing",
] }
env_logger = "0.10.0"
log = { version = "0.4.14" }
mockito = { workspace = true }
sp-core = { workspace = true, features = ["std"] }
starknet-core = { workspace = true }
starknet-ff = { workspace = true, default-features = false, features = [
    "alloc",
    "serde",
] }
starknet_api = { workspace = true, default-features = false }
tokio = { workspace = true, features = ["macros", "test-util", "parking_lot"] }
# test_utils = { path = "./test_utils", optional = true }
hex = "0.4"
mp-block = { workspace = true }
mp-commitments = { workspace = true }
mp-felt = { workspace = true }
mp-hashers = { workspace = true }
mp-transactions = { workspace = true, features = ["client"] }
mc-commitment-state-diff = { workspace = true }
validator = { workspace = true, features = ["derive"] }
sc-consensus-manual-seal.workspace = true
futures = { workspace = true, default-features = true }
parity-scale-codec = { workspace = true, features = [
  "derive",
] }

[dev-dependencies]
# test_utils = { path = "./test_utils" }
