[package]
edition = "2021"
name = "pallet-starknet-runtime-api"
version = "0.1.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
# Deoxys primitives
mp-felt = { workspace = true, features = ["parity-scale-codec", "serde"] }

# Starknet
starknet_api = { workspace = true }

# Substrate
parity-scale-codec = { workspace = true, features = ["derive"] }
scale-info = { workspace = true, features = ["derive"] }
sp-api = { workspace = true }
sp-runtime = { workspace = true }

[features]
default = ["std"]
std = [
  "mp-felt/std",
  "parity-scale-codec/std",
  "scale-info/std",
  "sp-api/std",
  "sp-runtime/std",
]
