[package]
edition = "2021"
name = "pallet-starknet-runtime-api"
version = "0.1.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
# Deoxys primitives
mp-contract = { workspace = true, features = [
  "parity-scale-codec",
  "scale-info",
] }
mp-felt = { workspace = true, features = ["parity-scale-codec", "serde"] }
mp-simulations = { workspace = true, features = [
  "parity-scale-codec",
  "scale-info",
] }
mp-transactions = { workspace = true, features = [
  "parity-scale-codec",
  "scale-info",
] }
pallet-starknet = { workspace = true }

# Starknet
blockifier = { workspace = true }
hashbrown = { workspace = true }
starknet_api = { workspace = true }

# Substrate
parity-scale-codec = { workspace = true, features = ["derive"] }
scale-info = { workspace = true, features = ["derive"] }
sp-api = { workspace = true }
sp-arithmetic = { workspace = true }
sp-runtime = { workspace = true }

[features]
default = ["std"]
std = [
  "mp-contract/std",
  "mp-felt/std",
  "mp-simulations/std",
  "mp-transactions/std",
  "parity-scale-codec/std",
  "scale-info/std",
  "sp-api/std",
  "sp-arithmetic/std",
  "sp-runtime/std",
]
