[package]
name = "dp-felt"
version.workspace = true
edition.workspace = true
license = "MIT"
description = "Deoxys felt type"
authors = { workspace = true }
repository = { workspace = true }

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]

[dependencies]
cairo-vm = { workspace = true }
primitive-types.workspace = true
starknet-core = { workspace = true }
starknet-ff = { workspace = true }
starknet-types-core = { workspace = true }
starknet_api = { workspace = true }
thiserror-no-std = { workspace = true }

# Optional
serde = { workspace = true, features = ["derive"] }
serde_with = { workspace = true }
