[package]
authors.workspace = true
edition.workspace = true
name = "mp-genesis-config"
repository.workspace = true
version.workspace = true

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
mp-felt = { workspace = true, features = ["parity-scale-codec", "serde"] }

blockifier = { workspace = true, features = ["testing"] }

# third party
derive_more = { workspace = true, features = ["constructor"] }
hex = { workspace = true }
lazy_static = { workspace = true }
serde = { workspace = true, features = ["derive"] }
serde_with = { workspace = true }
starknet-core = { workspace = true }
starknet-crypto = { workspace = true, features = ["alloc"] }

# optional
starknet-providers = { workspace = true, optional = true }

[features]
default = ["std"]
std = ["starknet-providers"]
