[package]
name = "mp-types"
description = "Deoxys substrate types"
authors.workspace = true
edition.workspace = true
repository.workspace = true
version.workspace = true

[dependencies]
primitive-types.workspace = true
