[package]
name = "dc-metrics"
version.workspace = true
edition.workspace = true
description = "Deoxys prometheus service"
authors = ["Kasar <https://github.com/kasarlabs>"]
homepage = "https://github.com/kasarlabs/deoxys"
license = "MIT"
publish = false
repository = "https://github.com/kasarlabs/deoxys"

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]

[dependencies]
anyhow.workspace = true
log.workspace = true
thiserror.workspace = true
tokio.workspace = true

hyper.workspace = true
prometheus.workspace = true
