name: Task - Integration Tests

on:
  workflow_dispatch:
  workflow_call:

jobs:
  coverage:
    permissions:
      pull-requests: write
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v4
      - uses: Swatinem/rust-cache@v2 # use a different cache key as coverae uses custom rustc args
      - uses: dtolnay/rust-toolchain@master
        with:
          toolchain: 1.78
      - name: Setup build deps
        run: |
          sudo apt-get update
          sudo apt-get install -y clang llvm libudev-dev protobuf-compiler
      - uses: rui314/setup-mold@v1
      - name: Install cargo-llvm-cov
        uses: taiki-e/install-action@cargo-llvm-cov
      - name: Install nextest
        uses: taiki-e/install-action@nextest

      - uses: software-mansion/setup-scarb@v1
        with:
          scarb-version: "2.8.1"

      - uses: foundry-rs/foundry-toolchain@v1
        with:
          version: nightly
      - name: Launch Anvil
        run: anvil --fork-url $ANVIL_FORK_URL --fork-block-number $ANVIL_BLOCK_NUMBER &
        env:
          ANVIL_FORK_URL: "https://eth.merkle.io"
          ANVIL_BLOCK_NUMBER: 20395662
      - name: Wait for Anvil to be ready
        run: |
          while ! nc -z localhost 8545; do
            sleep 1
          done

      - name: Build and run tests
        run: |
          source <(cargo llvm-cov show-env --export-prefix)
          cargo build --bin madara --profile dev
          export COVERAGE_BIN=$(realpath target/debug/madara)
          rm -f target/madara-* lcov.info
          cargo nextest --profile dev

      - name: Generate coverage info
        run: |
          source <(cargo llvm-cov show-env --export-prefix)
          cargo llvm-cov report --cobertura --output-path coverage.cobertura.xml

      - name: Display coverage
        uses: ewjoachim/coverage-comment-action@v1
        continue-on-error: true
        with:
          GITHUB_TOKEN: ${{ github.token }}
          COVERAGE_FILE: coverage.cobertura.xml

      - name: Coveralls
        uses: coverallsapp/github-action@v2
        with:
          files: coverage.cobertura.xml
          debug: true