---
name: Task - Linters

on:
  workflow_dispatch:
  workflow_call:

jobs:
  prettier:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Run prettier
        run: |-
          npx prettier --check .

  markdown-lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: avto-dev/markdown-lint@v1
        with:
          config: "./.markdownlint.json"
          args: "."
          ignore: "./target"

  toml-lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout toml files
        uses: actions/checkout@v4
      - name: Run toml check
        run: npx @taplo/cli@0.5.2 fmt --config ./taplo/taplo.toml --check
