---
name: Workflow - Pull Request

on:
  workflow_dispatch:
  pull_request:
    branches: [main]

concurrency:
  group: pr-checks-${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:
  changelog:
    name: Enforce CHANGELOG
    uses: ./.github/workflows/changelog.yml

  linters:
    name: Run linters
    uses: ./.github/workflows/linters.yml
    needs: changelog

  rust_check:
    name: Run check
    uses: ./.github/workflows/rust-check.yml
    needs: changelog

  linters_cargo:
    name: Run Cargo linters
    uses: ./.github/workflows/linters-cargo.yml
    needs: rust_check

  rust_test:
    name: Run Cargo tests
    uses: ./.github/workflows/rust-test.yml
    needs: rust_check

  coverage:
    name: Run Coverage
    uses: ./.github/workflows/coverage.yml
    needs: changelog
