---
name: Workflow - Push

on:
  workflow_dispatch:
  push:
    branches: [main]

jobs:
  linters:
    name: Run linters
    uses: ./.github/workflows/linters.yml

  rust_check:
    name: Run check
    uses: ./.github/workflows/rust-check.yml
