name: Create Release

on:
  push:
    tags:
      - "v*.*.*" # Triggers on version tags like v1.0.0

permissions:
  contents: write  # Add this line to grant write permissions to contents

jobs:
  create_release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Create GitHub Release
        uses: ncipollo/release-action@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          tag: ${{ github.ref_name }}
          name: Release ${{ github.ref_name }}
          commit: ${{ github.sha }}
          draft: false
          prerelease: false
          generateReleaseNotes: true
