---
name: Task - Run Cargo tests

on:
  workflow_dispatch:
  workflow_call:

jobs:
  rust_test:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v4
      - run: rustup toolchain install nightly-2023-08-24 --profile minimal
      - uses: Swatinem/rust-cache@v2
        with:
          shared-key: "cache"

      - name: Run unit tests
        run: |
          cargo test
