---
name: Task - Run check

on:
  workflow_dispatch:
  workflow_call:

jobs:
  rust_check:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v4
      - uses: Swatinem/rust-cache@v2
        with:
          shared-key: "cache"
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly-2023-08-24
          profile: minimal

      - name: Check the project
        run: |
          cargo check --release --workspace
