---
name: Task - Run Cargo tests

on:
  workflow_dispatch:
  workflow_call:

jobs:
  rust_test:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v3
      - uses: Swatinem/rust-cache@v2
        with:
          shared-key: "cache"
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly-2023-08-24
          profile: minimal

      - name: Run unit tests
        run: |
          cargo test
