---
name: Task - Run check

on:
  workflow_dispatch:
  workflow_call:

jobs:
  rust_check:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@master
        with:
          toolchain: nightly-2023-08-24
          components: rustfmt, clippy

      - uses: Swatinem/rust-cache@v2
        with:
          shared-key: "cache"

      - name: Setup build deps
        run: |
          sudo apt-get update
          sudo apt-get install -y clang llvm libudev-dev protobuf-compiler libasound2-dev

      - name: Check the project
        run: |
          cargo check --workspace

      - name: Format and clippy
        run: |
          cargo fmt -- --check
          cargo clippy --workspace --tests --no-deps -- -D warnings

      - name: Run unit tests
        run: |
          cargo test
