---
name: Task - Run check

on:
  workflow_dispatch:
  workflow_call:

jobs:
  rust_check:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v4
      - run: rustup toolchain install nightly-2023-08-24 --profile minimal
      - uses: Swatinem/rust-cache@v2
        with:
          shared-key: "cache"

      - name: Check the project
        run: |
          cargo check --release --workspace
